### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by mlebeur** [bihealth/varfish-db-downloader#2]
Hi,
I am using varfish-db-downloader which is a wonderfull tool.
But some links seems no more working.
I am updating these and adding the management of hg38.
But I have seen that some databases as mtDB/ MITOMAP/ ... are present in the varfish-server-background-db-20201006.tar.gz file but not describe in varfish-db-downloader .
Can you update the online version of this downloader please ?
If not, it remains a really nice work.
Cheers,
Manuel LEBEURRIER

**Comment by stolpeo** [comment]
Hello Manuel,

thank you for your interest, and apologize the late response! I will look into that next week and propose a solution.

Best,
  Oliver

**Comment by stolpeo** [comment]
Dear @mlebeur ,

I updated repository to now contain the latest changes. Thanks for pointing that out! I hope everything runs smoothly now. Please let us know if there are still troubles with the links, and I will look into that!

Have a nice weekend,
Cheers,
  Oliver

**Comment by mlebeur** [comment]
Hello,

Thanks a lot for your nice work.

Cheers,

Manuel
